### PR TITLE
Filter search & pagination

### PR DESCRIPTION
**Pull request by thecalcc**
## Checklist

- [x] This pull request is not adding new forms that use redux
- [ ] This pull request is adding missing TypeScript types to modified code segments where it's easy to do so with confidence

### CODE REVIEW

**Comment by thecalcc** [comment]
Type better before merging.

**Comment by thecalcc** [comment]
image
image

**Comment by thecalcc** [comment]
@fritzSF Moving "Show more" below the pagination doesn't make sense, as it's responsible for the content on the current page. Next page might have 5 items and show more won't be displayed. Also "show more" is totally independent from the pagination component. It's rendered as a child to it.

**Review by tomaskikutis — APPROVED** [review]

**Comment by tomaskikutis** [comment]
check CI

**Pull request merged**
