### PR TITLE
Folder creation on topic save

### PR DESCRIPTION
**Pull request by thecalcc**
CPCN-263

### CODE REVIEW

**Comment by tomaskikutis** [comment]
Could you add a video on how it works? I'd be useful to do for all PRs where features are added.

Also improve typescript types.

* don't use `any` for [new code](https://github.com/superdesk/newsroom-core/pull/586/files#diff-3d082b3dd36abe0c1cce509179e097067d854fb9e46e62a85ee0b3c08984e11dR89)
* add types for code you modified. [example](https://github.com/superdesk/newsroom-core/pull/586/files#diff-a7254ad079c6ebfaed5f00b4d7a2ecebfe168de2955c82cc9373ecd681978554R250) - I find it hard to believe you didn't find out types for `data` and `folder` while working on it :)

**Comment by thecalcc** [comment]
Video of how the feature works: 

https://github.com/superdesk/newsroom-core/assets/45574768/523d979b-d5da-464b-ba88-2255b0e69364

**Comment by tomaskikutis** [comment]
> Video of how the feature works:

I think we should auto-select the folder after creation

**Comment by thecalcc** [comment]
> > Video of how the feature works:
> 
> I think we should auto-select the folder after creation

done

**Review by tomaskikutis — APPROVED** [review]

**Pull request merged**
